### ISSUE TITLE
syntax error crashes cli on `specs` crate

### ISSUE THREAD

**Issue by cpdean** [cpdean/cargo-danger#5]
```
thread 'main' panicked at 'dunno Error { start_span: Span, end_span: Span, message: "expected `,`" }', /home/conrad/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-danger-0.2.1/src/main.rs:57:17
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:495
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:353
   7: cargo_danger::main
   8: std::rt::lang_start::{{closure}}
   9: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  10: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  11: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  12: main
  13: __libc_start_main
  14: _start
```

**Comment by cpdean** [comment]
sort of fixed by https://github.com/cpdean/cargo-danger/commit/41d410b13e2fd796122910fedfb07ad41b4ce5ac#diff-639fbc4ef05b315af92b4d836c31b023R810
